import "./globals.css";

import type { Metadata } from "next";

import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="pb-[20px]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
